bestviewproj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("usershome.urls")),
    path("", include("adminshome.urls")),
    path("", include("adminproductmanagement.urls")),
    path("", include("adminusermanagement.urls")),
    path("", include("userprofile.urls")),
    path("", include("userproduct.urls")),
    path("", include("user_order_and_payment.urls")),
    path("", include("admin_order_and_payment.urls")),
    path("", include("paypal.standard.ipn.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userproduct/urls.py
from django import views
from django.urls import path
from . import views

app_name = "userproduct"

urlpatterns = [
    path("product_details/<int:pk>/", views.product_details, name="product_details"),
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("cart/<int:cart_id>/", views.cart, name="cart"),
    path(
        "delete_from_cart/<int:variant_id>/",
        views.delete_from_cart,
        name="delete_from_cart",
    ),
    path("clear_cart/<int:cart_id>/", views.clear_cart, name="clear_cart"),
    path("update_cart_item/", views.update_cart_item, name="update_cart_item"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("add_to_wishlist/", views.add_to_wishlist, name="add_to_wishlist"),
    path(
        "delete-wishlist-item/", views.delete_wishlist_item, name="delete-wishlist-item"
    ),
]

userprofile/urls.py
from django import views
from django.urls import path
from . import views

app_name = "userprofile"

urlpatterns = [
    path("profile/<int:user_id>/", views.profile, name="profile"),
    path("edit_profile/<int:user_id>", views.edit_profile, name="edit_profile"),
    path("change_password/", views.change_password, name="change_password"),
    path("address/", views.address, name="address"),
    path("add_address/", views.add_address, name="add_address"),
    path("add_address/<str:address_type>/", views.add_address, name="add_address"),
    path("edit_address/<int:address_id>", views.edit_address, name="edit_address"),
    path(
        "delete_address/<int:address_id>", views.delete_address, name="delete_address"
    ),
    path("orders/", views.orders, name="orders"),
    path("cancel_order/<int:item_id>/", views.cancel_order, name="cancel_order"),
    path("delete_account/<int:user_id>/", views.delete_account, name="delete_account"),
    path("return_order/<int:item_id>/", views.return_order, name="return_order"),
    path("wallet/", views.wallet, name="wallet"),
    path("cash_deposit_page/", views.cash_deposit_page, name="cash_deposit_page"),
    path("deposit/", views.deposit, name="deposit"),
    path("cash_withdraw_page/", views.cash_withdraw_page, name="cash_withdraw_page"),
    path("withdraw/", views.withdraw, name="withdraw"),
    path("transaction_history/", views.transaction_history, name="transaction_history"),
    path("coupon/", views.coupon, name="coupon"),
    path(
        "download_invoice/<int:item_id>/",
        views.download_invoice,
        name="download_invoice",
    ),
]

usershome/urls.py
from django import views
from django.urls import path
from . import views
from .views import about_us

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.signin, name="signin"),
    path("register/", views.signup, name="signup"),
    path("otpverify/", views.verify_otp, name="verify_otp"),
    path("logout/", views.signout, name="signout"),
    path("shop/", views.shop, name="shop"),
    path("about_us/", about_us.as_view(), name="about_us"),
    path("filter_products/", views.filter_products, name="filter_products"),
    path("forgot_password/", views.forgot_password, name="forgot_password"),
    path(
        "forgot_password_verify_otp/",
        views.forgot_password_verify_otp,
        name="forgot_password_verify_otp",
    ),
    path(
        "forgot_change_password/",
        views.forgot_change_password,
        name="forgot_change_password",
    ),
    path("del_info/", views.del_info, name="del_info"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path(
        "terms_and_conditions/", views.terms_and_conditions, name="terms_and_conditions"
    ),
    path("customer_service", views.customer_service, name="customer_service"),
    path("contact_us/", views.contact_us, name="contact_us"),
]

userprofile/models.py
from django.db import models
from usershome.models import CustomUser
from django.core.validators import RegexValidator
from django.dispatch import receiver
from django.db.models.signals import post_save
from django.utils import timezone

# Create your models here.


class Address(models.Model):
    house_or_building_name = models.CharField()
    street_address = models.CharField()
    city = models.CharField()
    district = models.CharField()
    pincode_regex = RegexValidator(
        regex=r"^\d{6}$", message="Pincode must be 6 'digits'"
    )
    pincode = models.CharField(max_length=6, validators=[pincode_regex])
    state = models.CharField()
    phone_regex = RegexValidator(
        regex=r"^\d{10}$", message="Phone number must be 10 'digits'"
    )
    phone_no = models.CharField(max_length=10, validators=[phone_regex])
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-id"]


class Wallet(models.Model):
    balance = models.IntegerField(default=20)
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)


@receiver(post_save, sender=CustomUser)
def create_user_wallet(sender, instance, created, **kwargs):
    if created:
        wallet = Wallet.objects.create(user=instance)
        WalletTransactions.objects.create(
            type="Credit", amount=20, date=timezone.now(), wallet=wallet, user=instance
        )


post_save.connect(create_user_wallet, sender=CustomUser)


class WalletTransactions(models.Model):
    amount = models.IntegerField()
    type = models.CharField()
    date = models.DateField(auto_now_add=True)
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-id"]

    @staticmethod
    def save_transaction(type, amount, wallet, user):
        WalletTransactions.objects.create(
            type=type, amount=amount, wallet=wallet, user=user
        )

userprofile/forms.py
from django import forms
from usershome.models import CustomUser
from .models import Address


class EditProfileForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name"]


class AddAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = [
            "house_or_building_name",
            "street_address",
            "city",
            "district",
            "pincode",
            "state",
            "phone_no",
        ]

        def clean_house_or_building_name(self):
            house_or_building_name = self.cleaned_data.get("house_or_building_name")
            # Check if house_or_building_name contains any digits
            if any(char.isdigit() for char in house_or_building_name):
                raise forms.ValidationError(
                    "House or building name cannot contain numbers."
                )
            return house_or_building_name

userprofile/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from usershome.models import CustomUser
from .models import Address, Wallet, WalletTransactions
from django.contrib.auth.decorators import login_required
from .forms import EditProfileForm, AddAddressForm
from django.contrib import messages
from django.contrib.auth.forms import PasswordChangeForm
from django.views.decorators.cache import never_cache
from userproduct.models import CartItem, Cart
from user_order_and_payment.models import Order, OrderItems
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from adminproductmanagement.models import Coupons, ProductVariant
from django.db.models import Q
import os
from dotenv import load_dotenv
load_dotenv()

# Create your views here.


@never_cache
@login_required(login_url="signin")
def profile(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)
    cart = Cart.objects.filter(user=request.user).first()
    cart_items = CartItem.objects.filter(cart=cart)

    if cart_items is not None:
        cart_count = cart_items.count()
    else:
        cart_count = 0

    context = {
        "user": user,
        "cart_items": cart_items,
        "cart": cart,
        "cart_count": cart_count,
    }

    return render(request, "userprofile/profile.html", context)


@never_cache
@login_required(login_url="signin")
def edit_profile(request, user_id):
    user = get_object_or_404(CustomUser, id=user_id)
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request, "Profile Updated")
            return redirect("userprofile:profile", user_id)
    else:
        form = EditProfileForm(instance=user)

    cart = Cart.objects.filter(user=request.user).first()
    cart_items = CartItem.objects.filter(cart=cart)

    if cart_items is not None:
        cart_count = cart_items.count()
    else:
        cart_count = 0

    context = {
        "cart_items": cart_items,
        "cart": cart,
        "form": form,
        "cart_count": cart_count,
    }

    return render(request, "userprofile/edit_profile.html", context)


@never_cache
@login_required(login_url="signin")
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Password Changed Successfully")
            return redirect("signin")
    else:
        form = PasswordChangeForm(request.user)

    cart = Cart.objects.filter(user=request.user).first()
    cart_items = CartItem.objects.filter(cart=cart)

    if cart_items is not None:
        cart_count = cart_items.count()
    else:
        cart_count = 0

    context = {
        "cart_items": cart_items,
        "cart": cart,
        "form": form,
        "cart_count": cart_count,
    }

    return render(request, "userprofile/change_password.html", context)


@never_cache
@login_required(login_url="signin")
def address(request):
    user = request.user
    addresses = Address.objects.filter(user=user)
    cart = Cart.objects.filter(user=request.user).first()
    cart_items = CartItem.objects.filter(cart=cart)

    if cart_items is not None:
        cart_count = cart_items.count()
    else:
        cart_count = 0

    context = {
        "cart_items": cart_items,
        "cart": cart,
        "addresses": addresses,
        "cart_count": cart_count,
    }

    return render(request, "userprofile/address.html", context)


@never_cache
@login_required(login_url="signin")
def add_address(request, address_type=None):
    if request.method == "POST":
        form = AddAddressForm(request.POST)
        if form.is_valid():
            pincode = form.cleaned_data.get("pincode")

            if pincode == "000000":
                messages.error(request, "Please enter a valid pincode.")
                return redirect("userprofile:add_address")

            city = form.cleaned_data.get("city")
            if not city.isalpha():
                messages.error(
                    request, "City name should contain only alphabetic characters."
                )
                return redirect("userprofile:add_address")

            # Perform custom validation for district
            district = form.cleaned_data.get("district")
            if not district.isalpha():
                messages.error(
                    request, "District name should contain only alphabetic characters."
                )
                return redirect("userprofile:add_address")

            state = form.cleaned_data.get("state")
            if not state.isalpha():
                messages.error(
                    request, "State name should contain only alphabetic characters."
                )
                return redirect("userprofile:add_address")

            address = form.save(commit=False)
            address.user = request.user
            address.save()
            messages.success(request, "New Address Added")
            if not address_type:
                return redirect("userprofile:address")
            else:
                return redirect("user_order_and_payment:order_address")
    else:
        form = AddAddressForm()

    cart = Cart.objects.filter(user=request.user).first()
    cart_items = CartItem.objects.filter(cart=cart)

    if cart_items is not None:
        cart_count = cart_items.count()
    else:
        cart_count = 0

    context = {
        "cart_items": cart_items,
        "cart": cart,
        "form": form,
        "cart_count": cart_count,
    }

    return render(request, "userprofile/add_address.html", context)


@never_cache
@login_required(login_url="signin")
def edit_address(request, address_id):
    address = get_object_or_404(Address, pk=address_id)
    if request.method == "POST":
        form = AddAddressForm(request.POST, instance=address)
        if form.is_valid():
            pincode = form.cleaned_data.get("pincode")

            if pincode == "000000":
                messages.error(request, "Please enter a valid pincode.")
                return redirect("userprofile:edit_address", address.id)

            city = form.cleaned_data.get("city")
            if not city.isalpha():
                messages.error(
                    request, "City name should contain only alphabetic characters."
                )
                return redirect("userprofile:edit_address", address.id)

            # Perform custom validation for district
            district = form.cleaned_data.get("district")
            if not district.isalpha():
                messages.error(
                    request, "District name should contain only alphabetic characters."
                )
                return redirect("userprofile:edit_address", address.id)

            state = form.cleaned_data.get("state")
            if not state.isalpha():
                messages.error(
                    request, "State name should contain only alphabetic characters."
                )
                return redirect("userprofile:edit_address", address.id)

            form.save()
            messages.success(request, "Address Edited")
            return redirect("userprofile:address")
    else:
        form = AddAddressForm(instance=address)

    cart = Cart.objects.filter(user=request.user).first()
    cart_items = CartItem.objects.filter(cart=cart)

    if cart_items is not None:
        cart_count = cart_items.count()
    else:
        cart_count = 0

    context = {
        "cart_items": cart_items,
        "cart": cart,
        "form": form,
        "cart_count": cart_count,
    }

    return render(request, "userprofile/edit_address.html", context)


@never_cache
@login_required(login_url="signin")
def delete_address(request, address_id):
    address = get_object_or_404(Address, pk=address_id)
    address.delete()
    messages.success(request, "Address Deleted")
    return redirect("userprofile:address")


@never_cache
@login_required(login_url="signin")
def orders(request):
    cart = Cart.objects.filter(user=request.user).first()
    cart_items = CartItem.objects.filter(cart=cart)
    cart_count = cart_items.count() if cart_items is not None else 0

    user = request.user
    orders = Order.objects.filter(user=user)
    orderitems = OrderItems.objects.filter(order__in=orders)

    for item in orderitems:
        item.total_price = item.product.price * item.quantity
        if item.subtotal < item.product.price * item.quantity:
            item.discounted = item.product.price * item.quantity - item.subtotal

    paginator = Paginator(orderitems, 3)
    page_number = request.GET.get("page")

    try:
        orderitems = paginator.page(page_number)
    except PageNotAnInteger:
        orderitems = paginator.page(1)
    except EmptyPage:
        orderitems = paginator.page(paginator.num_pages)

    context = {
        "orders": orders,
        "orderitems": orderitems,
        "cart_count": cart_count,
        "cart": cart,
        "cart_items": cart_items,
    }
    return render(request, "userprofile/orders.html", context)


@never_cache
@login_required(login_url="signin")
def cancel_order(request, item_id):
    wallet = Wallet.objects.get(user=request.user)
    item = OrderItems.objects.get(id=item_id)

    product_variant = item.product_variant
    product = ProductVariant.objects.get(pk=product_variant.pk)
    product.quantity += item.quantity
    product.save()

    item.order_status = "Cancelled"
    if item.payment_status == "Paid":
        wallet.balance += item.subtotal
        wallet.save()
        WalletTransactions.save_transaction(
            type="Credit", amount=item.subtotal, wallet=wallet, user=request.user
        )
    item.save()
    messages.success(request, "Your order has been cancelled")
    return redirect("userprofile:orders")

userprofile/templates/userprofile/invoice_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="icon" href="{% static 'user/images/favicon/favicon.webp' %}" sizes="32x32" />
    <link href="https://cdn.jsdelivr.net/npm/@mdi/font/css/materialdesignicons.min.css" rel="stylesheet">
    
    <style>
    table{
      border:1px solid black;
    }
</style>

    <title>Invoice</title>
  </head>
  <body>
    
  </div>
</nav>

{% block content %}

{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

userprofile/templates/userprofile/orders.html
{% extends 'usershome/base.html' %}
{% load static %}
{% block title %}Orders{% endblock %}
{% block content %}

<style>
    .table-container {
        overflow-x: auto; /* Enable horizontal scrolling */
        max-width: 100%; /* Limit the maximum width of the table */
    }
    .product-thumbnail {
        max-width: 100%; /* Adjust the maximum width for the product thumbnail */
        height: auto; /* Maintain aspect ratio */
    }
    .orange-text {
        color: orange;
    }
    
    .grey-text {
        color: grey;
    }
    
    .blue-text {
        color: blue; /* Adjust the color as needed */
    }

    .green-text {
        color: green;
    }
    
    .red-text {
        color: red;
    }
    .blue-text{
        color: blue;
    }
    .black-text{
        color: black;
    }
</style>

<div class="my-account-wrapper pb-100 pt-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!-- My Account Page Start -->
                <div class="myaccount-page-wrapper">
                    <!-- My Account Tab Menu Start -->
                    <div class="row">
                        <div class="col-lg-3 col-md-12">
                            <div class="myaccount-tab-menu nav" role="tablist">
                                <a href="{% url 'userprofile:profile' user_id=user.id %}">Dashboard</a>
                                <a href="{% url 'userprofile:orders' %}" class="active">Orders</a>
                                <a href="{% url 'userprofile:wallet' %}">Wallet</a>
                                <a href="{% url 'userprofile:address' %}">Address</a>
                                <a href="{% url 'userprofile:coupon' %}">Coupon</a>
                                <a href="{% url 'signout' %}">Logout</a>
                            </div>
                        </div>
                        <div class="col-lg-9 col-md-12" style="margin-top: .3%;">
                            <div class="tab-content" id="myaccountContent">
                                <h1 style="display: inline-block;">Orders</h1>                   
                                <div class="table-container"> <!-- Add a container for the table to enable horizontal scrolling -->
                                    {% if orders %}
                                    <table class="table table-bordered table-responsive">
                                        <tr>
                                            <th>Order ID</th>
                                            <th>Image</th>
                                            <th>Product</th>
                                            <th>Variant</th>
                                            <th>Price</th>
                                            <th>Quantity</th>
                                            <th>Total Price</th>
                                            <th>Promotions</th>
                                            <th>Grand Total</th>
                                            <th>Delivery Status</th>
                                            <th>Order Date</th>
                                            <th>Delivered Date</th>
                                            <th>Payment Method</th>
                                            <th>Payment Status</th>
                                            <th>Delivery Address</th>
                                            <th>Phone No.</th>
                                            <th>Action</th>
                                        </tr>
                                        {% for item in orderitems %}
                                        <tr>
                                            <td>{{ item.order.order_id }}</td>
                                            <td><img class="product-thumbnail" src="{{ item.product_variant.thumbnail.url }}" alt="Product Variant Thumbnail"></td>
                                            <td><a href="{% url 'userproduct:product_details' pk=item.product.pk %}">{{ item.product }}</a></td>
                                            <td>{{ item.product_variant.color }}</td>
                                            <td>${{ item.product.price }}</td>
                                            <td>{{ item.quantity }}</td>
                                            <td>${{ item.total_price }}</td>
                                            {% if item.discounted %}
                                            <td>${{ item.discounted }}</td> 
                                            {% else %}
                                            <td>No Discount</td>
                                            {% endif %}
                                            <td>${{ item.subtotal }}</td>
                                            <td class="{% if item.order_status == 'Pending' %}orange-text
                                                {% elif item.order_status == 'Dispatched' %}grey-text
                                                {% elif item.order_status == 'Shipped' %}black-text
                                                {% elif item.order_status == 'Delivered' %}green-text
                                                {% elif item.order_status == 'Cancelled' %}red-text
                                                {% elif item.order_status == 'Returned' %}blue-text
                                                {% endif %}">
                                                {{ item.order_status }}
                                            </td>
                                            <td>{{ item.order.orderdate }}</td>
                                            {% if item.deliverydate %}
                                            <td>{{ item.deliverydate }}</td>
                                            {% else %}
                                            <td>Not Delivered</td>
                                            {% endif %}
                                            <td>{{ item.order.paymentmethod }}</td>
                                            <td class="{% if item.payment_status == 'Paid' %}green-text
                                                {% elif item.payment_status == 'Refunded' %}blue-text
                                                {% elif item.payment_status == 'Abandoned' %}black-text
                                                {% else %}orange-text
                                                {% endif %}"
                                            >{{ item.payment_status }}</td>
                                            <td><address>
                                                {{ item.order.orderaddress.house_or_building_name }},
                                                {{ item.order.orderaddress.street_address }},
                                                {{ item.order.orderaddress.city }},
                                                {{ item.order.orderaddress.district }},
                                                {{ item.order.orderaddress.pincode }},
                                                {{ item.order.orderaddress.state }}.
                                            </address></td>
                                            <td>{{ item.order.orderaddress.phone_no }}</td>
                                            <td>{% if not item.order_status == 'Cancelled' and not item.order_status == 'Delivered' and not item.order_status == 'Returned' %}<a href="{% url 'userprofile:cancel_order' item_id=item.id %}"><button class="btn btn-danger">Cancel</button></a>{% endif %}  {% if item.order_status == 'Delivered' %}<a href="{% url 'userprofile:return_order' item_id=item.id %}"><button class="btn btn-danger" style="background-color: blue; border:none;">Return</button></a>
                                                <a href="{% url 'userprofile:download_invoice' item_id=item.id %}"><button class="btn btn-success mt-3" style="border:none;">Inovice</button></a>
                                                {% endif %}
                                        </td>
                                        </tr>
                                        {% endfor %}
                                    </table>

                                                                        
                                    {% else %}
                                    You have no Orders.
                                    {% endif %}
                                </div>  
                                {% if orders %}
                                <div class="pagination-style-1 mt-3">
                                    <ul>
                                        {% for i in orderitems.paginator.page_range %}
                                            {% if orderitems.number == i %}
                                                <li><a class="active" href="#">{{ i }}</a></li>
                                            {% else %}
                                                <li><a href="?page={{ i }}">{{ i }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                    </ul>
                                </div> 
                                {% endif %}                            
                            </div>
                            <!-- {% if orders %}
                            <div class="mt-5">
                            <p>*The payment status of the product is initially determined upon order placement and subsequently updated upon successful delivery to the customer. However, it remains unchanged in the event of a return or cancellation by the customer.</p>
                            </div>
                            {% endif %} -->
                        </div>                       
                    </div>
                </div> <!-- My Account Page End -->
            </div>
        </div>
    </div>
</div>

{% endblock %}

userprofile/templates/userprofile/wallet.html
{% extends 'usershome/base.html' %}
{% load static %}
{% block title %}Wallet{% endblock %}
{% block content %}

<div class="my-account-wrapper pb-100 pt-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <!-- My Account Page Start -->
                <div class="myaccount-page-wrapper">
                    <!-- My Account Tab Menu Start -->
                    <div class="row">
                        <div class="col-lg-3 col-md-12">
                            <div class="myaccount-tab-menu nav" role="tablist">
                                <a href="{% url 'userprofile:profile' user_id=user.id %}">Dashboard</a>
                                <a href="{% url 'userprofile:orders' %}">Orders</a>
                                <a href="{% url 'userprofile:wallet' %}" class="active">Wallet</a>
                                <a href="{% url 'userprofile:address' %}">Address</a>
                                <a href="{% url 'userprofile:coupon' %}">Coupon</a>
                                <a href="{% url 'signout' %}">Logout</a>
                            </div>
                        </div>
                        <div class="col-lg-5">
                            <div class="your-order-area">
                                <h3>Wallet</h3>
                                <div class="your-order-wrap gray-bg-4">
                                    <div class="your-order-info-wrap">
                                        <div class="your-order-info order-total">
                                            <ul>
                                                <li>Balance <span>${{ wallet.balance }} </span></li>
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="payment-method text-center">
                                        <a href="{% url 'userprofile:cash_deposit_page' %}"><button class="btn btn-success rounded"> Deposit <i class="fa fa-plus"></i></button></a>
                                        <a href="{% url 'userprofile:cash_withdraw_page' %}"><button class="btn btn-danger rounded"> Withdraw <i class="fa fa-minus"></i></button></a>
                                    </div>
                                </div>
                                <div class="Place-order btn-hover">
                                    <a href="{% url 'userprofile:transaction_history' %}">Transaction History</a>
                                </div>
                            </div>
                        </div> <!-- My Account Tab Content End -->
                    </div>
                </div> <!-- My Account Page End -->
            </div>
        </div>
    </div>
</div>

{% endblock %}