adminproductmanagement/urls.py
from django import views
from django.urls import path
from . import views


app_name = "adminproductmanagement"

urlpatterns = [
    path("manage_category/", views.manage_category, name="manage_category"),
    path("add_category/", views.add_category, name="add_category"),
    path("edit_category/<int:pk>/", views.edit_category, name="edit_category"),
    path("delete_category/<int:pk>/", views.delete_category, name="delete_category"),
    path("unlist_category/<int:pk>/", views.unlist_category, name="unlist_category"),
    path("unlisted_categories", views.unlisted_categories, name="unlisted_categories"),
    path("restore_category/<int:pk>/", views.restore_category, name="restore_category"),
    path("manage_brand/", views.manage_brand, name="manage_brand"),
    path("add_brand/", views.add_brand, name="add_brand"),
    path("edit_brand/<int:pk>/", views.edit_brand, name="edit_brand"),
    path("delete_brand/<int:pk>/", views.delete_brand, name="delete_brand"),
    path("unlist_brand/<int:pk>/", views.unlist_brand, name="unlist_brand"),
    path("unlisted_brands", views.unlisted_brands, name="unlisted_brands"),
    path("restore_brand/<int:pk>/", views.restore_brand, name="restore_brand"),
    path("manage_product/", views.manage_product, name="manage_product"),
    path("add_product/", views.add_product, name="add_product"),
    path("edit_product/<int:pk>", views.edit_product, name="edit_product"),
    path("delete_product/<int:pk>/", views.delete_product, name="delete_product"),
    path("unlist_product/<int:pk>/", views.unlist_product, name="unlist_product"),
    path("unlisted_products", views.unlisted_products, name="unlisted_products"),
    path("restore_product/<int:pk>/", views.restore_product, name="restore_product"),
    path("add_variant/<int:product_id>/", views.add_variant, name="add_variant"),
    path("edit_variant/<int:pk>/", views.edit_variant, name="edit_variant"),
    path("delete_variant/<int:pk>/", views.delete_variant, name="delete_variant"),
    path(
        "delete_variant_image/<int:pk>/",
        views.delete_variant_image,
        name="delete_variant_image",
    ),
    path(
        "delete_product_thumbnail/<int:pk>/",
        views.delete_product_thumbnail,
        name="delete_product_thumbnail",
    ),
    path(
        "add_category_offer/<int:category_id>/",
        views.add_category_offer,
        name="add_category_offer",
    ),
    path(
        "delete_category_offer/<int:offer_id>/",
        views.delete_category_offer,
        name="delete_category_offer",
    ),
    path(
        "edit_category_offer/<int:offer_id>/",
        views.edit_category_offer,
        name="edit_category_offer",
    ),
    path(
        "add_product_offer/<int:product_id>/",
        views.add_product_offer,
        name="add_product_offer",
    ),
    path(
        "delete_product_offer/<int:offer_id>/",
        views.delete_product_offer,
        name="delete_product_offer",
    ),
    path(
        "edit_product_offer/<int:offer_id>/",
        views.edit_product_offer,
        name="edit_product_offer",
    ),
]

bestviewproj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("usershome.urls")),
    path("", include("adminshome.urls")),
    path("", include("adminproductmanagement.urls")),
    path("", include("adminusermanagement.urls")),
    path("", include("userprofile.urls")),
    path("", include("userproduct.urls")),
    path("", include("user_order_and_payment.urls")),
    path("", include("admin_order_and_payment.urls")),
    path("", include("paypal.standard.ipn.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usershome/urls.py
from django import views
from django.urls import path
from . import views
from .views import about_us

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.signin, name="signin"),
    path("register/", views.signup, name="signup"),
    path("otpverify/", views.verify_otp, name="verify_otp"),
    path("logout/", views.signout, name="signout"),
    path("shop/", views.shop, name="shop"),
    path("about_us/", about_us.as_view(), name="about_us"),
    path("filter_products/", views.filter_products, name="filter_products"),
    path("forgot_password/", views.forgot_password, name="forgot_password"),
    path(
        "forgot_password_verify_otp/",
        views.forgot_password_verify_otp,
        name="forgot_password_verify_otp",
    ),
    path(
        "forgot_change_password/",
        views.forgot_change_password,
        name="forgot_change_password",
    ),
    path("del_info/", views.del_info, name="del_info"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path(
        "terms_and_conditions/", views.terms_and_conditions, name="terms_and_conditions"
    ),
    path("customer_service", views.customer_service, name="customer_service"),
    path("contact_us/", views.contact_us, name="contact_us"),
]

adminproductmanagement/forms.py
from django import forms
from .models import (
    Category,
    Brand,
    Product,
    ProductVariant,
    CategoryOffer,
    ProductOffer,
)


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = "__all__"


class BrandForm(forms.ModelForm):
    class Meta:
        model = Brand
        fields = "__all__"


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "__all__"
        exclude = ["offer_price"]

    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price is not None and price < 0:
            raise forms.ValidationError("Price cannot be negative.")
        return price


class ProductVariantForm(forms.ModelForm):
    class Meta:
        model = ProductVariant
        fields = "__all__"
        exclude = ["product"]

    def clean_quantity(self):
        quantity = self.cleaned_data.get("quantity")
        if quantity is not None and quantity < 0:
            raise forms.ValidationError("Quantity cannot be negative.")
        return quantity


class AddCategoryOfferForm(forms.ModelForm):
    class Meta:
        model = CategoryOffer
        fields = "__all__"
        exclude = ["category", "status"]


class AddProductOfferForm(forms.ModelForm):
    class Meta:
        model = ProductOffer
        fields = "__all__"
        exclude = ["product", "status"]

adminproductmanagement/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import (
    Category,
    Brand,
    Product,
    ProductVariant,
    Image,
    CategoryOffer,
    ProductOffer,
)
from .forms import (
    CategoryForm,
    BrandForm,
    ProductForm,
    ProductVariantForm,
    AddCategoryOfferForm,
    AddProductOfferForm,
)
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.db.models import Q
from django.views.decorators.cache import never_cache
from django.utils import timezone

# Create your views here.


@never_cache
@login_required(login_url="adminshome:adminsignin")
def manage_category(request):
    if request.user.is_superuser:
        categories = Category.objects.filter(is_listed=True)
        return render(
            request,
            "adminproductmanagement/manage_category.html",
            {"categories": categories},
        )
    else:
        return redirect("adminshome:adminsignin")


@never_cache
@login_required(login_url="adminshome:adminsignin")
def add_category(request):
    if request.user.is_superuser:
        form = CategoryForm()
        if request.method == "POST":
            form = CategoryForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, "New Category Added")
                return redirect("adminproductmanagement:manage_category")
        return render(
            request, "adminproductmanagement/add_category.html", {"form": form}
        )
    else:
        return redirect("adminshome:adminsignin")


@never_cache
@login_required(login_url="adminshome:adminsignin")
def edit_category(request, pk):
    if request.user.is_superuser:
        category = get_object_or_404(Category, pk=pk)
        if request.method == "POST":
            form = CategoryForm(request.POST, request.FILES, instance=category)
            if form.is_valid():
                form.save()
                messages.success(request, "Category Edited")
                return redirect("adminproductmanagement:manage_category")
        else:
            form = CategoryForm(instance=category)
            offers = CategoryOffer.objects.filter(category=category, status="Active")
        return render(
            request,
            "adminproductmanagement/edit_category.html",
            {"form": form, "category": category, "offers": offers},
        )
    else:
        return redirect("adminshome:adminsignin")


@login_required(login_url="adminshome:adminsignin")
def delete_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.delete()
    messages.success(request, "Category Deleted")
    return redirect("adminproductmanagement:manage_category")


@login_required(login_url="adminshome:adminsignin")
def unlist_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.is_listed = False
    category.save()
    messages.success(request, "Category Unlisted")
    return redirect("adminproductmanagement:manage_category")


@never_cache
@login_required(login_url="adminshome:adminsignin")
def unlisted_categories(request):
    if request.user.is_superuser:
        categories = Category.objects.filter(is_listed=False)
        return render(
            request,
            "adminproductmanagement/unlisted_categories.html",
            {"categories": categories},
        )
    else:
        return redirect("adminshome:adminsignin")


@login_required(login_url="adminshome:adminsignin")
def restore_category(request, pk):
    category = get_object_or_404(Category, pk=pk)
    category.is_listed = True
    category.save()
    messages.success(request, "Category Restored")
    return redirect("adminproductmanagement:unlisted_categories")


@never_cache
@login_required(login_url="adminshome:adminsignin")
def manage_brand(request):
    if request.user.is_superuser:
        brands = Brand.objects.filter(is_listed=True)
        return render(
            request, "adminproductmanagement/manage_brand.html", {"brands": brands}
        )
    else:
        return redirect("adminshome:adminsignin")


@never_cache
@login_required(login_url="adminshome:adminsignin")
def add_brand(request):
    if request.user.is_superuser:
        form = BrandForm()
        if request.method == "POST":
            form = BrandForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, "New Brand Added")
                return redirect("adminproductmanagement:manage_brand")
        return render(request, "adminproductmanagement/add_brand.html", {"form": form})
    else:
        return redirect("adminshome:adminsignin")


@never_cache
@login_required(login_url="adminshome:adminsignin")
def edit_brand(request, pk):
    if request.user.is_superuser:
        brand = get_object_or_404(Brand, pk=pk)
        if request.method == "POST":
            form = BrandForm(request.POST, request.FILES, instance=brand)
            if form.is_valid():
                form.save()
                messages.success(request, "Brand Edited")
                return redirect("adminproductmanagement:manage_brand")
        else:
            form = BrandForm(instance=brand)
        return render(
            request,
            "adminproductmanagement/edit_brand.html",
            {"form": form, "brand": brand},
        )
    else:
        return redirect("adminshome:adminsignin")


@login_required(login_url="adminshome:adminsignin")
def delete_brand(request, pk):
    brand = get_object_or_404(Brand, pk=pk)
    brand.delete()
    messages.success(request, "Brand Deleted")
    return redirect("adminproductmanagement:manage_brand")


@login_required(login_url="adminshome:adminsignin")
def unlist_brand(request, pk):
    brand = get_object_or_404(Brand, pk=pk)
    brand.is_listed = False
    brand.save()
    messages.success(request, "Brand Unlisted")
    return redirect("adminproductmanagement:manage_brand")


@never_cache
@login_required(login_url="adminshome:adminsignin")
def unlisted_brands(request):
    if request.user.is_superuser:
        brands = Brand.objects.filter(is_listed=False)
        return render(
            request, "adminproductmanagement/unlisted_brands.html", {"brands": brands}
        )
    else:
        return redirect("adminshome:adminsignin")


@login_required(login_url="adminshome:adminsignin")
def restore_brand(request, pk):
    brand = get_object_or_404(Brand, pk=pk)
    brand.is_listed = True
    brand.save()
    messages.success(request, "Brand Restored")
    return redirect("adminproductmanagement:unlisted_brands")


@never_cache
@login_required(login_url="adminshome:adminsignin")
def manage_product(request):
    if request.user.is_superuser:
        query = request.GET.get("q")
        products = Product.objects.filter(is_listed=True)

        if query:
            query = query.replace(" ", "")
            products = products.filter(
                Q(name__icontains=query)
                | Q(category__name__icontains=query)
                | Q(brand__name__icontains=query)
                | Q(type__icontains=query)
            )

        context = {"products": products, "query": query}

        return render(request, "adminproductmanagement/manage_product.html", context)
    else:
        return redirect("adminshome:adminsignin")


@never_cache
@login_required(login_url="adminshome:adminsignin")
def add_product(request):
    if request.user.is_superuser:
        form = ProductForm()
        if request.method == "POST":
            form = ProductForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, "New Product Added")
                return redirect("adminproductmanagement:manage_product")
        return render(
            request, "adminproductmanagement/add_product.html", {"form": form}
        )
    else:
        return redirect("adminshome:adminsignin")


@never_cache
@login_required(login_url="adminshome:adminsignin")
def edit_product(request, pk=None):
    if request.user.is_superuser:
        product = get_object_or_404(Product, pk=pk)
        variants = ProductVariant.objects.filter(product=product)
        offers = ProductOffer.objects.filter(product=product, status="Active")  # Move outside of the if statement
        
        if request.method == "POST":
            form = ProductForm(request.POST, request.FILES, instance=product)
            if form.is_valid():
                form.save()
                messages.success(request, "Product Edited")
                return redirect("adminproductmanagement:manage_product")
        else:
            form = ProductForm(instance=product)
        
        return render(
            request,
            "adminproductmanagement/edit_product.html",
            {"form": form, "product": product, "variants": variants, "offers": offers},
        )
    else:
        return redirect("adminshome:adminsignin")



@login_required(login_url="adminshome:adminsignin")
def delete_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.delete()
    messages.success(request, "Product Deleted")
    return redirect("adminproductmanagement:manage_product")


@login_required(login_url="adminshome:adminsignin")
def unlist_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.is_listed = False
    product.save()
    messages.success(request, "Product Unlisted")
    return redirect("adminproductmanagement:manage_product")


@login_required(login_url="adminshome:adminsignin")
def restore_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    product.is_listed = True
    product.save()
    messages.success(request, "Product Restored")
    return redirect("adminproductmanagement:unlisted_products")


@never_cache

adminproductmanagement/templates/adminproductmanagement/edit_category.html
{% extends 'adminshome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Edit Category
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Edit Category</h4>
                <form method="post" enctype="multipart/form-data" action="{% url 'adminproductmanagement:edit_category' pk=category.pk %}">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <button type="submit" class="btn btn-success rounded">Update</button>
                </form>
            </div>
        </div>
    </div>

    <div class="col-lg-6 col-md-12 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
              <div>
                <div class="d-flex justify-content-between">
                    <h4 class="card-title">Manage Offers</h4>
                    <a href="{% url 'adminproductmanagement:add_category_offer' category_id=category.id %}">
                        <button type="button" class="btn btn-danger btn-icon-text">
                            <i class="mdi mdi-plus btn-icon-prepend"></i> Add
                        </button>
                    </a>
                </div>
                {% if offers %}
                <div class="table-responsive">
                    
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>Discount</th>
                                    <th>Valid From</th>
                                    <th>Valid To</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for offer in offers %}
                                    <tr>
                                        <td>{{ offer.discount_percentage }}%</td>
                                        <td>{{ offer.valid_from }}</td>
                                        <td>{{ offer.valid_to }}</td>
                                        <td>
                                          <a href="{% url 'adminproductmanagement:edit_category_offer' offer_id=offer.id %}"><button class="btn btn-primary mb-2">Edit</button></a>
                                          <br>
                                          <a href="{% url 'adminproductmanagement:delete_category_offer' offer_id=offer.id %}"><button class="btn btn-danger mb-2">Delete</button></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <p>No Offers found for this Category.</p>
                    
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

adminproductmanagement/templates/adminproductmanagement/manage_category.html
{% extends 'adminshome/base.html' %}
{% load static %}

{% block title %}Manage Category{% endblock %}

{% block content %}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <div style="display: flex; justify-content: space-between;">
          <h4 class="card-title">Manage Category</h4>
          <a href="{% url 'adminproductmanagement:unlisted_categories' %}"><button type="button" class="btn btn-icon-text" style="background-color: grey;">
            Unlisted Categories </button></a>
          <a href="{% url 'adminproductmanagement:add_category' %}"><button type="button" class="btn btn-danger btn-icon-text">
              <i class="mdi mdi-plus btn-icon-prepend"></i> Add </button></a>
        </div>
        <div class="table-responsive">
          {% if categories %}
          <table class="table table-bordered" style="background-color: #f2f2f2;">
              <thead>
                  <tr>
                      <th> Name </th>
                      <th> Image </th>
                      <th> Action </th>
                  </tr>
              </thead>
              <tbody>
                  {% for category in categories %}
                  <tr>
                      <td> {{ category.name }} </td>
                      <td> <img src="{{ category.image.url }}" alt="" style="width: 150px; height: auto;"> </td> <!-- Adjust the width as needed -->
                      <td>
                          <a href="{% url 'adminproductmanagement:edit_category' pk=category.pk %}" class="btn-link">
                              <button type="button" class="btn btn-outline-secondary btn-icon-text custom-btn" style="background-color: grey;">Edit <i class="mdi mdi-file-check btn-icon-append"></i></button>
                          </a>
                          <a href="{% url 'adminproductmanagement:unlist_category' pk=category.pk %}" style="margin-bottom: 10px; ">
                            <button type="submit" class="btn btn-danger btn-icon-text" style="border: none; background-color: black;">Unlist <i class="fas fa-folder-minus"></i></button>
                          </a>
                      </td>
                  </tr>
                  {% endfor %}
              </tbody>
          </table>
          {% else %}
          No Categories Found.
          {% endif %}
        </div>
      
      </div>
    </div>
  </div>

  

{% endblock %}

adminproductmanagement/templates/adminproductmanagement/manage_product.html
{% extends 'adminshome/base.html' %}
{% load static %}

{% block title %}Manage Product{% endblock %}

{% block content %}
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <div style="display: flex; justify-content: space-between;">
          <h4 class="card-title">Manage Product</h4>
          <a href="{% url 'adminproductmanagement:unlisted_products' %}"><button type="button" class="btn btn-icon-text" style="background-color: grey;">
              Unlisted Products </button></a>
          <a href="{% url 'adminproductmanagement:add_product' %}"><button type="button" class="btn btn-danger btn-icon-text">
              <i class="mdi mdi-plus btn-icon-prepend"></i> Add </button></a>
        </div>
        <ul class="navbar-nav w-100">
            <li class="nav-item w-100">
                <form method="GET" action="{% url 'adminproductmanagement:manage_product' %}" class="search-form form-inline">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="text" name="q" value="{% if query %}{{ query }}{% endif %}" placeholder="Search Product" class="form-control">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-success">Search</button>
                        </div>
                    </div>
                </form>
            </li>
        </ul>  
        <div class="table-responsive mt-5">
          {% if products %}
          <table class="table table-bordered" style="background-color: #f2f2f2;">
              <thead>
                  <tr>
                    <th> Brand </th>
                    <th> Name </th>
                    <th> Thumbnail </th>
                    <th> Price </th>
                    <th>Offer Price</th>
                    <th> Type </th>
                    <th> Category </th>
                    <th> Action </th>
                  </tr>
              </thead>
              <tbody>
                  {% for product in products %}
                  <tr>
                      <td> {{ product.brand }} </td> 
                      <td> {{ product.name }} </td>
                      <td>
                        {% if product.thumbnail %}
                            <img src="{{ product.thumbnail.url }}" style="height: 100px; width: 100px;" alt="">
                        {% else %}
                            No Thumbnail Available
                        {% endif %}
                      </td>
                      <td> ${{ product.price }} </td>
                      {% if product.offer_price %}
                      <td>${{ product.offer_price }}</td>
                      {% else %}
                      <td> No offer </td>
                      {% endif %}

                      <td> {{ product.type }} </td>
                      <td> {{ product.category }} </td>
                      <td>
                        <div style="display: flex; flex-direction: column;">
                            <a href="{% url 'adminproductmanagement:edit_product' pk=product.pk %}" class="btn-link my-2">
                                <button type="button" class="btn btn-outline-secondary btn-icon-text custom-btn" style="background-color: grey;">Edit <i class="mdi mdi-file-check btn-icon-append"></i></button>
                            </a>                    
                            <a href="{% url 'adminproductmanagement:unlist_product' pk=product.pk %}" style="margin-bottom: 10px;">
                                <button type="submit" class="btn btn-danger btn-icon-text" style="border: none; background-color: black;">Unlist <i class="fas fa-folder-minus"></i></button>
                            </a>
                        </div>
                      </td>                    
                  </tr>
                  {% endfor %}
              </tbody>
          </table>
          {% else %}
            No Products Found.
          {% endif %}
        </div>
      
      </div>
    </div>
  </div>

  

{% endblock %}

adminproductmanagement/templates/adminproductmanagement/manage_variant.html
{% extends 'adminshome/base.html' %}
{% load static %}

{% block title %}Manage Variant{% endblock %}

{% block content %}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <div style="display: flex; justify-content: space-between;">
          <h4 class="card-title">Manage Variant</h4>
          <a href="{% url 'adminproductmanagement:add_variant' %}"><button type="button" class="btn btn-danger btn-icon-text">
              <i class="mdi mdi-plus btn-icon-prepend"></i> Add </button></a>
        </div>
        <div class="table-responsive">
          <table class="table table-bordered">
              <thead>
                  <tr>
                      <th> Color </th>
                      <th> Quantity </th>
                      <th> Thumbnail </th>
                      <th> Product </th>
                      <th> Action </th>
                  </tr>
              </thead>
              <tbody>
                  {% for variant in variants %}
                  <tr>
                      <td> {{ variant.color }} </td>
                      <td> {{ variant.quantity }} </td>
                      <td> <img src="{{ variant.thumbnail.url }}" alt="" style="width: 150px; height: auto;"> </td> <!-- Adjust the width as needed -->
                      <td> {{ variant.product }} </td>
                      <td>
                          <a href="{% url 'adminproductmanagement:edit_variant' pk=variant.pk %}" class="btn-link">
                              <button type="button" class="btn btn-outline-secondary btn-icon-text custom-btn">Edit <i class="mdi mdi-file-check btn-icon-append"></i></button>
                          </a>
                          <a href="{% url 'adminproductmanagement:delete_variant' pk=variant.pk %}">
                            <button type="submit" class="btn btn-danger btn-icon-text">Delete <i class="mdi mdi-delete btn-icon-append"></i></button>
                          </a>
                      </td>
                  </tr>
                  {% endfor %}
              </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  

{% endblock %}

adminproductmanagement/templates/adminproductmanagement/unlisted_brands.html
{% extends 'adminshome/base.html' %}
{% load static %}

{% block title %}Unlisted Brands{% endblock %}

{% block content %}
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <div style="display: flex; justify-content: space-between;">
          <h4 class="card-title">Unlisted Brands</h4>
          <a href="{% url 'adminproductmanagement:manage_brand' %}"><button type="button" class="btn btn-icon-text" style="background-color: grey;">
              Manage Brand </button></a>
        </div> 
        {% if brands %}
        <div class="table-responsive mt-5">
          <table class="table table-bordered" style="background-color: #f2f2f2;">
              <thead>
                  <tr>
                    <th> Name </th>
                    <th> Image </th>
                    <th> Action </th>
                  </tr>
              </thead>
              <tbody>
                  {% for brand in brands %}
                  <tr>
                      <td> {{ brand.name }} </td>
                      <td> <img src="{{ brand.image.url }}" style="height: 100px; width: 100px;" alt=""> </td> <!-- Adjust the width as needed -->
                      <td>
                        <div style="display: flex; flex-direction: column;">
                            <a href="{% url 'adminproductmanagement:edit_brand' pk=brand.pk %}" class="btn-link my-2">
                                <button type="button" class="btn btn-outline-secondary btn-icon-text custom-btn" style="background-color: grey;">Edit <i class="mdi mdi-file-check btn-icon-append"></i></button>
                            </a>                    
                            <a href="{% url 'adminproductmanagement:restore_brand' pk=brand.pk %}" style="margin-bottom: 10px;">
                                <button type="submit" class="btn btn-danger btn-icon-text" style="border: none; background-color: black;">Restore <i class="fas fa-folder-plus"></i></button>
                            </a>
                            <a href="{% url 'adminproductmanagement:delete_brand' pk=brand.pk %}">
                                <button type="submit" class="btn btn-danger btn-icon-text">Delete <i class="mdi mdi-delete btn-icon-append"></i></button>
                            </a>
                        </div>
                      </td>                    
                  </tr>
                  {% endfor %}
              </tbody>
          </table>
        </div>
      {% else %}
      <h5 class="mt-3">No Unlisted Brands Found.</h5>
      {% endif %}
      </div>
    </div>
  </div>

  

{% endblock %}