bestviewproj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("usershome.urls")),
    path("", include("adminshome.urls")),
    path("", include("adminproductmanagement.urls")),
    path("", include("adminusermanagement.urls")),
    path("", include("userprofile.urls")),
    path("", include("userproduct.urls")),
    path("", include("user_order_and_payment.urls")),
    path("", include("admin_order_and_payment.urls")),
    path("", include("paypal.standard.ipn.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_order_and_payment/urls.py
from django import views
from django.urls import path
from . import views
from .views import payment_failed

app_name = "user_order_and_payment"

urlpatterns = [
    path("order_address/", views.order_address, name="order_address"),
    path("place_order/", views.place_order, name="place_order"),
    path("apply_coupon/", views.apply_coupon, name="apply_coupon"),
    path("payment_method/", views.payment_method, name="payment_method"),
    path("remove_coupon/", views.remove_coupon, name="remove_coupon"),
    path("payment_failed/", payment_failed.as_view(), name="payment_failed"),
]

userproduct/urls.py
from django import views
from django.urls import path
from . import views

app_name = "userproduct"

urlpatterns = [
    path("product_details/<int:pk>/", views.product_details, name="product_details"),
    path("add_to_cart/", views.add_to_cart, name="add_to_cart"),
    path("cart/<int:cart_id>/", views.cart, name="cart"),
    path(
        "delete_from_cart/<int:variant_id>/",
        views.delete_from_cart,
        name="delete_from_cart",
    ),
    path("clear_cart/<int:cart_id>/", views.clear_cart, name="clear_cart"),
    path("update_cart_item/", views.update_cart_item, name="update_cart_item"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("add_to_wishlist/", views.add_to_wishlist, name="add_to_wishlist"),
    path(
        "delete-wishlist-item/", views.delete_wishlist_item, name="delete-wishlist-item"
    ),
]

userprofile/urls.py
from django import views
from django.urls import path
from . import views

app_name = "userprofile"

urlpatterns = [
    path("profile/<int:user_id>/", views.profile, name="profile"),
    path("edit_profile/<int:user_id>", views.edit_profile, name="edit_profile"),
    path("change_password/", views.change_password, name="change_password"),
    path("address/", views.address, name="address"),
    path("add_address/", views.add_address, name="add_address"),
    path("add_address/<str:address_type>/", views.add_address, name="add_address"),
    path("edit_address/<int:address_id>", views.edit_address, name="edit_address"),
    path(
        "delete_address/<int:address_id>", views.delete_address, name="delete_address"
    ),
    path("orders/", views.orders, name="orders"),
    path("cancel_order/<int:item_id>/", views.cancel_order, name="cancel_order"),
    path("delete_account/<int:user_id>/", views.delete_account, name="delete_account"),
    path("return_order/<int:item_id>/", views.return_order, name="return_order"),
    path("wallet/", views.wallet, name="wallet"),
    path("cash_deposit_page/", views.cash_deposit_page, name="cash_deposit_page"),
    path("deposit/", views.deposit, name="deposit"),
    path("cash_withdraw_page/", views.cash_withdraw_page, name="cash_withdraw_page"),
    path("withdraw/", views.withdraw, name="withdraw"),
    path("transaction_history/", views.transaction_history, name="transaction_history"),
    path("coupon/", views.coupon, name="coupon"),
    path(
        "download_invoice/<int:item_id>/",
        views.download_invoice,
        name="download_invoice",
    ),
]

usershome/urls.py
from django import views
from django.urls import path
from . import views
from .views import about_us

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.signin, name="signin"),
    path("register/", views.signup, name="signup"),
    path("otpverify/", views.verify_otp, name="verify_otp"),
    path("logout/", views.signout, name="signout"),
    path("shop/", views.shop, name="shop"),
    path("about_us/", about_us.as_view(), name="about_us"),
    path("filter_products/", views.filter_products, name="filter_products"),
    path("forgot_password/", views.forgot_password, name="forgot_password"),
    path(
        "forgot_password_verify_otp/",
        views.forgot_password_verify_otp,
        name="forgot_password_verify_otp",
    ),
    path(
        "forgot_change_password/",
        views.forgot_change_password,
        name="forgot_change_password",
    ),
    path("del_info/", views.del_info, name="del_info"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path(
        "terms_and_conditions/", views.terms_and_conditions, name="terms_and_conditions"
    ),
    path("customer_service", views.customer_service, name="customer_service"),
    path("contact_us/", views.contact_us, name="contact_us"),
]

user_order_and_payment/views.py
from typing import Any
from django.shortcuts import redirect, render
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required
from userprofile.models import Address
from user_order_and_payment.models import OrderAddress, Order, OrderItems
from userproduct.models import Cart, CartItem
from userprofile.models import Wallet, WalletTransactions
from django.contrib import messages
from adminproductmanagement.models import Coupons, ProductVariant, UsedCoupons
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from django.views.generic import TemplateView
import os
from dotenv import load_dotenv
load_dotenv()

# Create your views here.


@never_cache
@login_required(login_url="signin")
def order_address(request):
    user = request.user
    try:
        cart = Cart.objects.get(user=user)
    except:
        return redirect("home")
    cart_items = CartItem.objects.filter(cart=cart)

    for item in cart_items:
        if item.quantity > item.product_variant.quantity:
            messages.error(
                request,
                f"{ item.product.name } { item.product_variant.color } quantity exceeds available quantity",
            )
            return redirect("userproduct:cart", cart.id)

    if cart_items is not None:
        cart_count = cart_items.count()
    else:
        cart_count = 0

    addresses = Address.objects.filter(user=user)

    return render(
        request,
        "user_order_and_payment/order_address.html",
        {
            "addresses": addresses,
            "cart": cart,
            "cart_items": cart_items,
            "cart_count": cart_count,
        },
    )


@never_cache
@login_required(login_url="signin")
def payment_method(request):

    applied_coupon_code = request.session.get("applied_coupon_code")

    available_coupons = Coupons.objects.filter(code=applied_coupon_code).exists()

    if not available_coupons:
        if "applied_coupon_code" in request.session:
            del request.session["applied_coupon_code"]
            cart = Cart.objects.get(user=request.user)
            cart_items = CartItem.objects.filter(cart=cart)

            original_total = sum(
                item.product.price * item.quantity for item in cart_items
            )
            cart.total = original_total
            cart.save()

            for item in cart_items:
                if not item.product.offer_price:
                    original_subtotal = item.product.price * item.quantity
                    item.subtotal = original_subtotal
                    item.save()
                else:
                    original_subtotal = item.product.offer_price * item.quantity
                    item.subtotal = original_subtotal
                    item.save()
    if available_coupons:
        coupon = Coupons.objects.get(code=applied_coupon_code)
    user = request.user
    try:
        cart = Cart.objects.get(user=user)
    except:
        return redirect("home")
    cart_items = CartItem.objects.filter(cart=cart)
    for item in cart_items:
        if item.quantity > item.product_variant.quantity:
            messages.error(
                request,
                f"{ item.product.name } { item.product_variant.color } quantity exceeds available quantity",
            )
            return redirect("userproduct:cart", cart.id)

    if cart_items is not None:
        cart_count = cart_items.count()
    else:
        cart_count = 0

    if request.method == "POST":
        selected_address_id = request.POST.get("selected_address_id")
        if selected_address_id:
            selected_address = Address.objects.get(pk=selected_address_id)
            request.session["selected_address"] = selected_address.id

            return redirect("user_order_and_payment:payment_method")

    if applied_coupon_code is None:
        paypal_client_id = os.getenv("PAYPAL_CLIENT_ID")
        context = {"cart": cart, "cart_items": cart_items, "cart_count": cart_count, "paypal_client_id": paypal_client_id}
    else:
        paypal_client_id = os.getenv("PAYPAL_CLIENT_ID")
        context = {
            "cart": cart,
            "cart_items": cart_items,
            "cart_count": cart_count,
            "applied_coupon_code": applied_coupon_code,
            "coupon":coupon,
            "paypal_client_id": paypal_client_id
        }

    return render(request, "user_order_and_payment/payment_method.html", context)


@never_cache
@login_required(login_url="signin")
def place_order(request):
    user = request.user
    try:
        cart = Cart.objects.get(user=user)
    except:
        return redirect("home")
    cart_items = CartItem.objects.filter(cart=cart)

    for item in cart_items:
        if item.quantity > item.product_variant.quantity:
            messages.error(
                request,
                f"{ item.product.name } { item.product_variant.color } quantity exceeds available quantity",
            )
            return redirect("userproduct:cart", cart.id)

    payment_method = request.POST.get("payment_method")

    selected_address_id = request.session.get("selected_address")
    selected_address = (
        Address.objects.get(pk=selected_address_id) if selected_address_id else None
    )

    order_address = None
    if selected_address:
        order_address = OrderAddress.objects.create(
            house_or_building_name=selected_address.house_or_building_name,
            street_address=selected_address.street_address,
            city=selected_address.city,
            district=selected_address.district,
            pincode=selected_address.pincode,
            state=selected_address.state,
            phone_no=selected_address.phone_no,
        )

    order = Order.objects.create(
        total=cart.total,
        user=user,
        paymentmethod=payment_method,
        orderaddress=order_address,
    )

    order_items = []

    for cart_item in cart_items:
        if order.paymentmethod == "Cash On Delivery" and order.total > 200:
            messages.error(
                request, "Orders exceeding $200 are not eligible for Cash On Delivery."
            )
            return redirect("user_order_and_payment:payment_method")
        elif order.paymentmethod == "Cash On Delivery":
            payment_status = "Pending"
        elif order.paymentmethod == "Wallet":
            payment_status = "Paid"

            wallet = Wallet.objects.get(user=request.user)

            if wallet.balance >= order.total:
                wallet.balance -= cart_item.subtotal
                wallet.save()

            else:
                messages.error(
                    request,
                    "Please ensure that the total amount of your order does not exceed the balance available in your wallet.",
                )
                return redirect("userproduct:cart", cart.id)
        else:
            payment_status = "Paid"

        order_item = OrderItems.objects.create(
            quantity=cart_item.quantity,
            subtotal=cart_item.subtotal,
            product=cart_item.product,
            product_variant=cart_item.product_variant,
            order=order,
            payment_status=payment_status,
        )
        order_items.append(order_item)

        product_variant = order_item.product_variant
        product = ProductVariant.objects.get(pk=product_variant.pk)
        product.quantity -= order_item.quantity
        product.save()

    if order.paymentmethod == "Wallet":
        wallet = Wallet.objects.get(user=request.user)
        WalletTransactions.save_transaction(
            type="Debit", amount=order.total, wallet=wallet, user=request.user
        )
    cart.delete()

    context = {
        "order_items": order_items,
        "order_address": order_address,
        "order": order,
        "payment_method": payment_method,
    }

    return render(request, "user_order_and_payment/order_confirm.html", context)


class payment_failed(TemplateView):
    template_name = "user_order_and_payment/payment_failed.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        cart = None
        cart_items = None
        cart_count = 0

        if self.request.user.is_authenticated:
            cart = Cart.objects.filter(user=self.request.user).first()
            cart_items = CartItem.objects.filter(cart=cart)
            cart_count = cart_items.count()

        context["cart"] = cart
        context["cart_count"] = cart_count
        context["cart_items"] = cart_items
        return context


def apply_coupon(request):
    if request.method == "POST":
        cart = Cart.objects.get(user=request.user)
        cart_items = CartItem.objects.filter(cart=cart)
        for item in cart_items:
            if item.quantity > item.product_variant.quantity:
                messages.error(
                    request,
                    f"{ item.product.name } { item.product_variant.color } quantity exceeds available quantity",
                )
                return redirect("userproduct:cart", cart.id)
        applied_coupon_code = request.POST.get("entered_coupon")

        try:
            coupon = Coupons.objects.exclude(status="Inactive").get(
                code=applied_coupon_code
            )

            if timezone.now().date() > coupon.valid_to:
                messages.error(request, "Coupon has expired")
                return redirect("user_order_and_payment:payment_method")

        except ObjectDoesNotExist:
            messages.error(request, "Invalid Coupon Entered")
            return redirect("user_order_and_payment:payment_method")

        if cart.total >= coupon.minimum_amount:
            used_coupon = UsedCoupons.objects.filter(user=request.user, code=coupon)

            if used_coupon:
                messages.error(request, "Coupon already redeemed")

user_order_and_payment/templates/user_order_and_payment/order_address.html
{% extends 'usershome/base.html' %}
{% load static %}

{% block title %}Order Address{% endblock %}

{% block content %}

<div class="container mb-5">
    <div class="row justify-content-center">
        <div class="col-12 col-xl-8">
            <div class="checkout-details">
                <div class="card">
                    <div class="card-body">
                        <div class="p-3">
                            <h2 class="mb-0">Shipping Address</h2>
                            <div class="my-3 border-bottom"></div>
                            <div class="form-body">
                                <div class="row g-3">
                                        <div class="card shadow-none border mb-0 p-2 bg-light">
                                                <div class="card-body">
                                                    <div class="d-flex d-flex justify-content-between">
                                                        <h5 class="mb-4">Choose an address</h5>	
                                                        <a href="{% url 'userprofile:add_address' address_type='checkout' %}">
                                                            <button class="btn text-white" style="background-color: #e97730; color: white; transition: background-color 0.3s ease;" onmouseover="this.style.backgroundColor='black'" onmouseout="this.style.backgroundColor='#e97730'">Add</button>
                                                        </a>                                                        
                                                    </div>
                                                    <form method="post" action="{% url 'user_order_and_payment:payment_method' %}">
                                                        {% csrf_token %}
                                                    <div class="row">
                                                        {% for address in addresses %}
                                                        <div class="col-12 col-lg-5 border m-2 pt-2 bg-white">
                                                            <div class="form-check">
                                                                <input class="form-check-input" type="radio" name="selected_address_id" id="address{{ address.id }}" value="{{ address.id }}" required>
                                                                    <address>
                                                                        {{ address.house_or_building_name }}<br>
                                                                        {{ address.street_address }}<br>
                                                                        {{ address.city }}<br>
                                                                        {{ address.district }}<br>
                                                                        {{ address.pincode }}<br>
                                                                        {{ address.state }}<br>
                                                                        {{ address.phone_no }}
                                                                    </address>
                                                            </div>
                                                        </div>
                                                        {% endfor %}
                                                        
                                                    </div>
                                                </div>
                                        </div>
                                    <div class="col-md-6">
                                        <div class="d-grid">	
                                            <a href="{% url 'userproduct:cart' cart_id=cart.id %}" class="btn btn-ecomm" style="background-color: black; color: white; transition: background-color 0.3s ease;" onmouseover="this.style.backgroundColor='#e97730'" onmouseout="this.style.backgroundColor='black'"><i class='bx bx-chevron-left'></i>Back to Cart</a>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="d-grid">
                                            {% if addresses %}	
                                            <button type="submit" class="btn btn-ecomm" style="background-color: #e97730; color: white; transition: background-color 0.3s ease; font-weight:bold;" onmouseover="this.style.backgroundColor='black'" onmouseout="this.style.backgroundColor='#e97730'">Proceed to Checkout<i class='bx bx-chevron-right'></i></button>
                                            {% endif %}
                                        </div>
                                    </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user_order_and_payment/templates/user_order_and_payment/order_confirm.html
{% extends 'usershome/base.html' %}
{% load static %}

{% block title %}Order Success{% endblock %}

{% block content %}

<!--start page wrapper -->
<div class="page-wrapper mb-5">
    <div class="page-content">
      <!--start shop cart-->
      <section class="py-4">
        <div class="container">
          <div class="card py-3 mt-sm-3">
            <div class="card-body text-center">
              <i class="fa-sharp fa-solid fa-circle-check fa-4x mb-3" style="color: #45c90d;"></i>
              <h2 class="h4 pb-3">Your order has been placed!</h2>
              <h2>Track your order from 'Orders' Page.</h2>
              <p>Incase of any Enquiries regarding the order, Contact us and use this Order ID: {{ order.order_id }}. </p>
              <a href="{% url 'home' %}"><button class="btn theme-color" style="background-color: #e97730; color: white; transition: background-color 0.3s ease; font-weight:bold;" onmouseover="this.style.backgroundColor='black'" onmouseout="this.style.backgroundColor='#e97730'">Home</button></a>
            </div>
            </div>
          </div>
        </div>
      </section>
      <!--end shop cart-->
    </div>
  </div>
  <!--end page wrapper -->


{% if payment_method == 'PayPal' %}
<!-- Include SweetAlert2 -->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
  <script>
      Swal.fire({
          icon: 'success',
          title: 'Transaction completed!',
          showConfirmButton: false,
          timer: 4000, 
      });
  </script>
{% endif %}

{% endblock %}

user_order_and_payment/templates/user_order_and_payment/payment_failed.html
{% extends 'usershome/base.html' %}
{% load static %}

{% block title %}Payment Failed{% endblock %}

{% block content %}
<style>
    .payment-failed-container {
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;
        height: 80vh;
        text-align: center;
    }
    .payment-failed-heading {
        font-size: 3em; /* Increase heading font size */
        margin-bottom: 20px; /* Add space below heading */
    }
    .payment-failed-message {
        font-size: 1.5em; /* Increase message font size */
        margin-bottom: 30px; /* Add space below message */
    }
    .btn-primary {
        font-size: 1.5em; /* Set font size for Home button */
        margin-top: 10px;
        border: none; /* Remove border */
        padding: 10px 20px; /* Add padding */
        border-radius: 5px; /* Add border-radius */
        text-decoration: none; /* Remove underline */
        cursor: pointer;
    }
    .btn-home {
        font-size: 1.5em; /* Set font size for Home button */
        margin-top: 10px; /* Add margin-top */
        background-color: #e97730; /* Orange background color */
        color: white; /* White text color */
        border: none; /* Remove border */
        padding: 10px 20px; /* Add padding */
        border-radius: 5px; /* Add border-radius */
        text-decoration: none; /* Remove underline */
        cursor: pointer; /* Change cursor on hover */
    }
</style>

<div class="payment-failed-container">
    <i class="fa-solid fa-ban mb-3" style="color: #ff0000; font-size: 5em;"></i>
    <h1 class="payment-failed-heading">Payment Failed</h1>
    <p class="payment-failed-message">Sorry, your payment could not be processed. Please try again later or choose a different payment method.</p>
    <a href="{% url 'user_order_and_payment:payment_method' %}" class="btn btn-primary" style="font-size: 1.5em;">Try Again</a>
    <a href="{% url 'home' %}"><button class="btn btn-home theme-color mt-3" style="font-size: 1.5em; background-color: #e97730; color: white; transition: background-color 0.3s ease;" onmouseover="this.style.backgroundColor='black'" onmouseout="this.style.backgroundColor='#e97730'">Home</button></a> <!-- Increase button font size -->
</div>
{% endblock %}

user_order_and_payment/templates/user_order_and_payment/payment_method.html
{% extends 'usershome/base.html' %}
{% load static %}

{% block title %}Payment Method{% endblock %}

{% block content %}

<style>
    .center-wrapper {
        display: flex;
        justify-content: center;
        align-items: center;
        height: 170vh;
    }
    .grand-total-wrap {
        margin-top: 5%; /* Adjust margin top as needed */
        height:100%;
        text-align: center;
    }
</style>

<div class="center-wrapper">
    <div class="col-lg-6 col-md-6 col-sm-6 grand-total-wrap justify-content-center align-items-center">
            <div class="grand-total-content text-center mt-5">
                <span style="font-size: larger; font-weight:bold;">Select Payment Method</span>
                <div class="grand-shipping">

                    <form method="post" action="{% url 'user_order_and_payment:place_order' %}">
                        {% csrf_token %}
                        <button type="submit" type="button" class="btn btn-primary btn-lg btn-block mb-3" name="payment_method" value="Wallet" style="width: 100%; font-size: 125%;">Wallet <i class="fa-solid fa-wallet"></i></button>
                    </form>

                    <form id="order-form" method="post" action="{% url 'user_order_and_payment:place_order' %}"> 
                        {% csrf_token %}
                        <input type="hidden" id="payment-method-input" name="payment_method" value="">
                        <div id="paypal-button-container"></div>
                    </form>

                    <form method="post" action="{% url 'user_order_and_payment:place_order' %}">
                        {% csrf_token %}
                        <button type="submit" type="button" class="btn btn-dark btn-lg btn-block mb-3" name="payment_method" value="Cash On Delivery" style="width: 100%; font-size: 125%;">Cash On Delivery <i class="fa-solid fa-hand-holding-dollar"></i></button>
                    </form>
                    <p>Please be advised that Cash On Delivery (COD) is not available for orders exceeding $200. We apologize for any inconvenience this may cause and appreciate your understanding.</p>
                        

                    <div class="mt-5">
                        <h5 style="font-weight: bold;">Payable Amount - ${{ cart.total }}</h5>
                        {% if 'applied_coupon_code' in request.session %}
                            <h6 style="font-weight: bold;">{{ coupon.discount_percentage }}% off with coupon</h6>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="customer-zone mt-5">
                {% if 'applied_coupon_code' in request.session %}
                <p class="cart-page-title">Coupon Applied: {{ applied_coupon_code }}</p>
                <a href="{% url 'user_order_and_payment:remove_coupon' %}" class="btn btn-danger mt-3">Remove Coupon</a>
                
                {% else %}
                    <p class="cart-page-title">Have a coupon? <a class="checkout-click3" href="">Click here to enter your code</a></p>
                    <div class="checkout-login-info3">
                    <form method="post" action="{% url 'user_order_and_payment:apply_coupon' %}">
                        {% csrf_token %}
                        <input type="text" name="entered_coupon" placeholder="Coupon code">
                        <input type="submit" value="Apply Coupon">
                    </form>
                </div>
                {% endif %}
                
            </div>
            
            
            

            <p class="mt-3">*Applying a coupon provides a percentage-based discount on individual product subtotals, reflecting the reduced amount in the Payable amount.</p>
            
            <div class="grand-total-btn btn-hover">
                <button type="button" class="btn theme-color" onclick="window.location.href='{% url 'user_order_and_payment:order_address' %}'" style="background-color: black; color: white; transition: background-color 0.3s ease;" onmouseover="this.style.backgroundColor='#e97730'" onmouseout="this.style.backgroundColor='black'">Back to Address</button>
            </div>
    </div>
</div>

<!-- Include the PayPal JavaScript SDK -->
<script src="https://www.paypal.com/sdk/js?client-id={{ paypal_client_id }}&currency=USD"></script>

<!-- JavaScript code for PayPal buttons -->
<script>
    paypal.Buttons({
        createOrder: function(data, actions) {
            return actions.order.create({
                purchase_units: [{
                    amount: {
                        value: '{{ cart.total }}'
                    }
                }]
            });
        },
        onApprove: function(data, actions) {
            return actions.order.capture().then(function(details) {
                document.getElementById('payment-method-input').value = 'PayPal';
                document.getElementById('order-form').submit();
            });
        },
        onCancel: function(data) {
            window.location.href = '{% url "user_order_and_payment:payment_failed" %}';
        }
    }).render('#paypal-button-container');
</script>


{% endblock %}