admin_order_and_payment/urls.py
from django import views
from django.urls import path
from . import views


app_name = "admin_order_and_payment"

urlpatterns = [
    path("manage_order/", views.manage_order, name="manage_order"),
    path(
        "manage_order_status/<int:item_id>/",
        views.manage_order_status,
        name="manage_order_status",
    ),
    path(
        "update_order_status/<int:item_id>/",
        views.update_order_status,
        name="update_order_status",
    ),
]

adminproductmanagement/urls.py
from django import views
from django.urls import path
from . import views


app_name = "adminproductmanagement"

urlpatterns = [
    path("manage_category/", views.manage_category, name="manage_category"),
    path("add_category/", views.add_category, name="add_category"),
    path("edit_category/<int:pk>/", views.edit_category, name="edit_category"),
    path("delete_category/<int:pk>/", views.delete_category, name="delete_category"),
    path("unlist_category/<int:pk>/", views.unlist_category, name="unlist_category"),
    path("unlisted_categories", views.unlisted_categories, name="unlisted_categories"),
    path("restore_category/<int:pk>/", views.restore_category, name="restore_category"),
    path("manage_brand/", views.manage_brand, name="manage_brand"),
    path("add_brand/", views.add_brand, name="add_brand"),
    path("edit_brand/<int:pk>/", views.edit_brand, name="edit_brand"),
    path("delete_brand/<int:pk>/", views.delete_brand, name="delete_brand"),
    path("unlist_brand/<int:pk>/", views.unlist_brand, name="unlist_brand"),
    path("unlisted_brands", views.unlisted_brands, name="unlisted_brands"),
    path("restore_brand/<int:pk>/", views.restore_brand, name="restore_brand"),
    path("manage_product/", views.manage_product, name="manage_product"),
    path("add_product/", views.add_product, name="add_product"),
    path("edit_product/<int:pk>", views.edit_product, name="edit_product"),
    path("delete_product/<int:pk>/", views.delete_product, name="delete_product"),
    path("unlist_product/<int:pk>/", views.unlist_product, name="unlist_product"),
    path("unlisted_products", views.unlisted_products, name="unlisted_products"),
    path("restore_product/<int:pk>/", views.restore_product, name="restore_product"),
    path("add_variant/<int:product_id>/", views.add_variant, name="add_variant"),
    path("edit_variant/<int:pk>/", views.edit_variant, name="edit_variant"),
    path("delete_variant/<int:pk>/", views.delete_variant, name="delete_variant"),
    path(
        "delete_variant_image/<int:pk>/",
        views.delete_variant_image,
        name="delete_variant_image",
    ),
    path(
        "delete_product_thumbnail/<int:pk>/",
        views.delete_product_thumbnail,
        name="delete_product_thumbnail",
    ),
    path(
        "add_category_offer/<int:category_id>/",
        views.add_category_offer,
        name="add_category_offer",
    ),
    path(
        "delete_category_offer/<int:offer_id>/",
        views.delete_category_offer,
        name="delete_category_offer",
    ),
    path(
        "edit_category_offer/<int:offer_id>/",
        views.edit_category_offer,
        name="edit_category_offer",
    ),
    path(
        "add_product_offer/<int:product_id>/",
        views.add_product_offer,
        name="add_product_offer",
    ),
    path(
        "delete_product_offer/<int:offer_id>/",
        views.delete_product_offer,
        name="delete_product_offer",
    ),
    path(
        "edit_product_offer/<int:offer_id>/",
        views.edit_product_offer,
        name="edit_product_offer",
    ),
]

adminshome/urls.py
from django import views
from django.urls import path
from . import views


app_name = "adminshome"

urlpatterns = [
    path("adminsignin/", views.adminsignin, name="adminsignin"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("adminsignout/", views.adminsignout, name="adminsignout"),
    path("manage_banner/", views.manage_banner, name="manage_banner"),
    path("add_banner/", views.add_banner, name="add_banner"),
    path("edit_banner/<int:pk>/", views.edit_banner, name="edit_banner"),
    path("delete_banner/<int:pk>/", views.delete_banner, name="delete_banner"),
    path("manage_coupon/", views.manage_coupon, name="manage_coupon"),
    path("unlist_coupon/<int:coupon_id>", views.unlist_coupon, name="unlist_coupon"),
    path("unlisted_coupons/", views.unlisted_coupons, name="unlisted_coupons"),
    path("list_coupon/<int:coupon_id>", views.list_coupon, name="list_coupon"),
    path("add_coupon/", views.add_coupon, name="add_coupon"),
    path("download_pdf/", views.download_pdf, name="download_pdf"),
    path("get_revenue_data/", views.get_revenue_data, name="get_revenue_data"),
    path("get_data/", views.get_data, name="get_data"),
]

adminusermanagement/urls.py
from django import views
from django.urls import path
from . import views


app_name = "adminusermanagement"

urlpatterns = [
    path("userlist/", views.userlist, name="userlist"),
    path(
        "block_unblock_user/<int:user_id>/",
        views.block_unblock_user,
        name="block_unblock_user",
    ),
]

bestviewproj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("usershome.urls")),
    path("", include("adminshome.urls")),
    path("", include("adminproductmanagement.urls")),
    path("", include("adminusermanagement.urls")),
    path("", include("userprofile.urls")),
    path("", include("userproduct.urls")),
    path("", include("user_order_and_payment.urls")),
    path("", include("admin_order_and_payment.urls")),
    path("", include("paypal.standard.ipn.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usershome/urls.py
from django import views
from django.urls import path
from . import views
from .views import about_us

urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.signin, name="signin"),
    path("register/", views.signup, name="signup"),
    path("otpverify/", views.verify_otp, name="verify_otp"),
    path("logout/", views.signout, name="signout"),
    path("shop/", views.shop, name="shop"),
    path("about_us/", about_us.as_view(), name="about_us"),
    path("filter_products/", views.filter_products, name="filter_products"),
    path("forgot_password/", views.forgot_password, name="forgot_password"),
    path(
        "forgot_password_verify_otp/",
        views.forgot_password_verify_otp,
        name="forgot_password_verify_otp",
    ),
    path(
        "forgot_change_password/",
        views.forgot_change_password,
        name="forgot_change_password",
    ),
    path("del_info/", views.del_info, name="del_info"),
    path("privacy_policy/", views.privacy_policy, name="privacy_policy"),
    path(
        "terms_and_conditions/", views.terms_and_conditions, name="terms_and_conditions"
    ),
    path("customer_service", views.customer_service, name="customer_service"),
    path("contact_us/", views.contact_us, name="contact_us"),
]

adminshome/models.py
from django.db import models

# Create your models here.


class Banner(models.Model):
    name = models.CharField()
    image = models.ImageField(upload_to="banner_image/")

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-id"]

adminshome/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from .models import Banner
from .forms import BannerForm, AddCouponForm
from adminproductmanagement.models import Coupons
from user_order_and_payment.models import Order, OrderItems
from .render_pdf import render_to_pdf
from django.db.models import Sum
from datetime import datetime, timedelta

# Create your views here.


@never_cache
def adminsignin(request):
    if request.user.is_authenticated and request.user.is_superuser:
        return redirect("adminshome:dashboard")
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(request, username=username, password=password)

        if user:
            if user.is_superuser:
                login(request, user)
                messages.success(request, f"Welcome {username}")
                return redirect("adminshome:dashboard")
            else:
                messages.error(request, "You are not an admin")
                return redirect("adminshome:adminsignin")
        else:
            messages.error(request, "Invalid Username or Password")
            return redirect("adminshome:adminsignin")
    return render(request, "adminshome/adminsignin.html")


@login_required(login_url="adminshome:adminsignin")
def dashboard(request):
    if request.user.is_superuser:

        orders = Order.objects.all()
        paypal_orders = Order.objects.filter(paymentmethod="PayPal")
        cod_orders = Order.objects.filter(paymentmethod="Cash On Delivery")
        wallet_orders = Order.objects.filter(paymentmethod="Wallet")
        items = OrderItems.objects.filter(payment_status="Paid")
        top_items = (
            OrderItems.objects.filter(payment_status="Paid")
            .values("product__name", "product__price")
            .annotate(total_sold=Sum("quantity"))
            .order_by("-total_sold")[:5]
        )
        top_category = (
            OrderItems.objects.filter(payment_status="Paid")
            .values("product__category__name")
            .annotate(total_sold=Sum("quantity"))
            .order_by("-total_sold")
            .first()
        )
        top_brands = (
            OrderItems.objects.filter(payment_status="Paid")
            .values("product__brand__name")
            .annotate(total_sold=Sum("quantity"))
            .order_by("-total_sold")[:3]
        )

        discounted = 0
        grand_total = 0

        for item in items:
            item.total_price = item.product.price * item.quantity
            grand_total += item.subtotal
            if item.subtotal < item.product.price * item.quantity:
                item.discounted = item.product.price * item.quantity - item.subtotal
                discounted += item.product.price * item.quantity - item.subtotal

        paypal_order_items = OrderItems.objects.filter(
            order__in=paypal_orders, payment_status="Paid"
        )
        paypal_total_amount = sum(item.subtotal for item in paypal_order_items)

        cod_order_items = OrderItems.objects.filter(
            order__in=cod_orders, payment_status="Paid"
        )
        cod_total_amount = sum(item.subtotal for item in cod_order_items)

        wallet_order_items = OrderItems.objects.filter(
            order__in=wallet_orders, payment_status="Paid"
        )
        wallet_total_amount = sum(item.subtotal for item in wallet_order_items)

        order_items = OrderItems.objects.filter(order__in=orders, payment_status="Paid")
        total_amount = sum(item.subtotal for item in order_items)

        total_order = 0
        for order in order_items:
            total_order += 1

        context = {
            "paypal_total_amount": paypal_total_amount,
            "cod_total_amount": cod_total_amount,
            "wallet_total_amount": wallet_total_amount,
            "total_amount": total_amount,
            "total_order": total_order,
            "items": items,
            "discounted": discounted,
            "grand_total": grand_total,
            "top_items": top_items,
            "top_category": top_category,
            "top_brands": top_brands,
        }

        return render(request, "adminshome/dashboard.html", context)
    else:
        return redirect("adminshome:adminsignin")


def download_pdf(request):
    filter_type = request.GET.get("filter")
    start_date = request.GET.get("start_date") or None
    end_date = request.GET.get("end_date") or None

    if start_date == None and end_date == None:
        now = datetime.now()
        if filter_type == "yearly":
            start_date = datetime(now.year, 1, 1)
            end_date = datetime(now.year, 12, 31, 23, 59, 59, 999999)
        elif filter_type == "monthly":
            start_date = datetime(now.year, now.month, 1)
            end_date = datetime(now.year, now.month, now.day, 23, 59, 59, 999999)
        elif filter_type == "weekly":
            today = datetime.now()
            start_date = today - timedelta(days=today.weekday())
            end_date = start_date + timedelta(days=6)
        elif filter_type == "daily":
            start_date = datetime(now.year, now.month, now.day)
            end_date = datetime(now.year, now.month, now.day, 23, 59, 59, 999999)

    items = OrderItems.objects.filter(payment_status="Paid")
    if start_date is not None and end_date is not None:
        items = items.filter(
            order__orderdate__gte=start_date, order__orderdate__lte=end_date
        )

    grand_total = 0

    for item in items:
        item.total_price = item.product.price * item.quantity
        grand_total += item.subtotal
        if item.subtotal < item.product.price * item.quantity:
            item.discounted = item.product.price * item.quantity - item.subtotal

    results = []

    for item in items:
        result_item = {
            "product_name": item.product.name,
            "price": item.product.price,
            "quantity": item.quantity,
            "total_price": item.total_price,
            "subtotal": item.subtotal,
            "discounted_price": (
                item.discounted if hasattr(item, "discounted") else None
            ),
        }
        results.append(result_item)

    context = {
        "pagesize": "A4",
        "mylist": results,
        "grand_total": grand_total,
    }
    pdf = render_to_pdf("adminshome/sales_report_pdf.html", context)

    if pdf:
        response = HttpResponse(pdf, content_type="application/pdf")
        filename = "sales_report.pdf"
        content = f"attachment; filename={filename}"
        download = request.GET.get("download")
        if download:
            content = f"attachment; filename={filename}"
        response["Content-Disposition"] = content
        return response

    return HttpResponse("Failed to generate PDF", status=400)


def get_revenue_data(request):
    filter_type = request.GET.get("filter")
    start_date = request.GET.get("start_date") or None
    end_date = request.GET.get("end_date") or None

    if start_date is None and end_date is None:
        if filter_type == "yearly":
            start_date = datetime.now().replace(
                month=1, day=1, hour=0, minute=0, second=0, microsecond=0
            )
            end_date = datetime.now().replace(
                month=12, day=31, hour=23, minute=59, second=59, microsecond=999999
            )
        elif filter_type == "custom" and start_date and end_date:
            start_date = datetime.strptime(start_date, "%Y-%m-%d")
            end_date = datetime.strptime(end_date, "%Y-%m-%d").replace(
                hour=23, minute=59, second=59, microsecond=999999
            )
        elif filter_type == "monthly":
            start_date = datetime.now().replace(
                day=1, hour=0, minute=0, second=0, microsecond=0
            )
            end_date = datetime.now().replace(
                day=30, hour=23, minute=59, second=59, microsecond=999999
            )
        elif filter_type == "weekly":
            today = datetime.now()
            start_date = today - timedelta(days=today.weekday())
            end_date = start_date + timedelta(days=6)
        elif filter_type == "daily":
            start_date = datetime.now().replace(
                hour=0, minute=0, second=0, microsecond=0
            )
            end_date = datetime.now().replace(
                hour=23, minute=59, second=59, microsecond=999999
            )

    orders = (
        OrderItems.objects.filter(
            payment_status="Paid",
            order__orderdate__gte=start_date,
            order__orderdate__lte=end_date,
        )
        .order_by("-order__orderdate")
        .values("order__orderdate")
        .annotate(revenue=Sum("subtotal"))
    )

    data = {"labels": [], "revenue": []}
    for order in orders:
        data["labels"].append(order["order__orderdate"])
        data["revenue"].append(order["revenue"])

    return JsonResponse(data)


def get_data(request):
    filter_type = request.GET.get("filter")
    start_date = request.GET.get("start_date") or None
    end_date = request.GET.get("end_date") or None

    if start_date is None and end_date is None:
        if filter_type == "yearly":
            start_date = datetime.now().replace(
                month=1, day=1, hour=0, minute=0, second=0, microsecond=0
            )
            end_date = datetime.now().replace(
                month=12, day=31, hour=23, minute=59, second=59, microsecond=999999
            )
        elif filter_type == "custom" and start_date and end_date:
            start_date = datetime.strptime(start_date, "%Y-%m-%d")

adminshome/templates/adminshome/add_coupon.html
{% extends 'adminshome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Add Coupon{% endblock %}

{% block content %}

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Add Coupon</h4>
        <form class="" method="post" action="{% url 'adminshome:add_coupon' %}">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success rounded">Add</button>
        </form>
      </div>
    </div>
  </div>

  

{% endblock %}

adminshome/templates/adminshome/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  
<!-- Mirrored from themewagon.github.io/corona-free-dark-bootstrap-admin-template/pages/samples/blank-page.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 28 Jan 2024 05:11:46 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=utf-8" /><!-- /Added by HTTrack -->
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Base{% endblock %}</title>
    <!-- plugins:css -->
    <link rel="stylesheet" href="{% static 'admin/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin/vendors/css/vendor.bundle.base.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="{% static 'admin/vendors/jvectormap/jquery-jvectormap.css' %}">
    <link rel="stylesheet" href="{% static 'admin/vendors/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin/vendors/owl-carousel-2/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'admin/vendors/owl-carousel-2/owl.theme.default.min.css' %}">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End Plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="{% static 'admin/css/style.css' %}">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="{% static 'admin/images/favicon.png' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
  </head>
  <body>
    <div class="container-scroller">
      <!-- partial:../../partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
          <a class="sidebar-brand brand-logo" href="{% url 'adminshome:dashboard' %}"><i class="mdi mdi-home"></i></a>
          <a class="sidebar-brand brand-logo-mini" href="{% url 'adminshome:dashboard' %}"><i class="mdi mdi-home"></i></a>
        </div>
        <ul class="nav">
          <li class="nav-item profile">
            <div class="profile-desc">
              <div class="profile-pic">
                <div class="profile-name">
                  <h5 class="mb-0 font-weight-normal">Hamraz</h5>
                  <span>Admin</span>
                </div>
              </div>
            </div>
          </li>
          <li class="nav-item nav-category">
            <span class="nav-link">Navigation</span>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'adminshome:dashboard' %}">
              <span class="menu-icon">
                <i class="mdi mdi-speedometer"></i>
              </span>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
              <span class="menu-icon">
                <i class="mdi mdi-glasses"></i>
              </span>
              <span class="menu-title">Manage Products</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-basic">
              <ul class="nav flex-column sub-menu">
                <li class="nav-item"> <a class="nav-link" href="{% url 'adminproductmanagement:manage_category' %}">Category</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'adminproductmanagement:manage_brand' %}">Brand</a></li>
                <li class="nav-item"> <a class="nav-link" href="{% url 'adminproductmanagement:manage_product' %}">Product</a></li>
              </ul>
            </div>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'adminshome:manage_banner' %}">
              <span class="menu-icon">
                <i class="mdi mdi-laptop"></i>
              </span>
              <span class="menu-title">Manage Banners</span>
            </a>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'adminusermanagement:userlist' %}">
              <span class="menu-icon">
                <i class="mdi mdi-account"></i>
              </span> 
              <span class="menu-title">Manage Users</span>
            </a>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'admin_order_and_payment:manage_order' %}">
              <span class="menu-icon">
                <i class="mdi mdi-package-variant-closed"></i>
              </span> 
              <span class="menu-title">Manage Orders</span>
            </a>
          </li>
          <li class="nav-item menu-items">
            <a class="nav-link" href="{% url 'adminshome:manage_coupon' %}">
              <span class="menu-icon">
                <i class="fa-solid fa-ticket"></i>
              </span>
              <span class="menu-title">Manage Coupons</span>
            </a>
          </li>
        </ul>
      </nav>
      <!-- partial -->
      <div class="container-fluid page-body-wrapper">
        <!-- partial:../../partials/_navbar.html -->
        <nav class="navbar p-0 fixed-top d-flex flex-row">
          <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
            <a class="navbar-brand brand-logo-mini" href="{% url 'adminshome:dashboard' %}"><img src="{% static 'user/images/logo/logo.webp' %}" alt="logo" /></a>
          </div>
          <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
            <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
              <span class="mdi mdi-menu"></span>
            </button>
            
            <ul class="navbar-nav navbar-nav-right">
              <li class="nav-item dropdown">
                <a class="nav-link" id="profileDropdown" href="#" data-toggle="dropdown">
                  <div class="navbar-profile">
                    <p class="mb-0 d-none d-sm-block navbar-profile-name">Hamraz Hakeem</p>
                    <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                  </div>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item preview-item" href="{% url 'adminshome:adminsignout' %}">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-logout text-danger"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject mb-1">Log out</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                </div>
              </li>
            </ul>
            <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
              <span class="mdi mdi-format-line-spacing"></span>
            </button>
          </div>
        </nav>
        <!-- partial -->
        <div class="main-panel">
          
            <!-- content-wrapper ends -->
            <!-- partial:../../partials/_footer.html -->




            <div id="content">
              {% block content %}{% endblock %}
            </div>




          <!-- partial -->
        </div>
        <!-- main-panel ends -->
      </div>
      <!-- page-body-wrapper ends -->
    </div>
    <!-- container-scroller -->


    <!-- plugins:js -->
    <script src="{% static 'admin/vendors/js/vendor.bundle.base.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="{% static 'admin/js/off-canvas.js' %}"></script>
    <script src="{% static 'admin/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'admin/js/misc.js' %}"></script>
    <script src="{% static 'admin/js/settings.js' %}"></script>
    <script src="{% static 'admin/js/todolist.js' %}"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <!-- End custom js for this page -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- Plugin js for this page -->
    <script src="{% static 'admin/vendors/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'admin/vendors/progressbar.js/progressbar.min.js' %}"></script>
    <script src="{% static 'admin/vendors/jvectormap/jquery-jvectormap.min.js' %}"></script>
    <script src="{% static 'admin/vendors/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
    <script src="{% static 'admin/vendors/owl-carousel-2/owl.carousel.min.js' %}"></script>
    <!-- End plugin js for this page -->

    <!-- Custom js for this page -->
    <script src="{% static 'admin/js/dashboard.js' %}"></script>
    <!-- End custom js for this page -->
    <script src="{% static 'admin/js/chart.js' %}"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <!-- endinject -->
    {% if messages %}
          {% for message in messages %}
    <script>
              const Toast = Swal.mixin({
                  toast: true,
                  position: "top",
                  showConfirmButton: true,
                  timer: 4000,
                  timerProgressBar: false,
                  didOpen: (toast) => {
                      toast.onmouseenter = Swal.stopTimer;
                      toast.onmouseleave = Swal.resumeTimer;
                  }
              });
              Toast.fire({
                  icon: "{{ message.tags }}",  // You might need to map Django message tags to SweetAlert2 icons
                  title: "{{ message }}"
              });    
  </script>
  {% endfor %}
      {% endif %}
  </body>

<!-- Mirrored from themewagon.github.io/corona-free-dark-bootstrap-admin-template/pages/samples/blank-page.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 28 Jan 2024 05:11:46 GMT -->
</html>

adminshome/templates/adminshome/edit_banner.html
{% extends 'adminshome/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Edit Banner{% endblock %}

{% block content %}

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">Edit Banner</h4>
        <form class="" method="post" enctype="multipart/form-data" action="{% url 'adminshome:edit_banner' pk=banner.pk %}">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-success rounded">Update</button>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

adminshome/templates/adminshome/manage_banner.html
{% extends 'adminshome/base.html' %}
{% load static %}

{% block title %}Manage Banner{% endblock %}

{% block content %}

<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
      <div class="card-body">
        <div style="display: flex; justify-content: space-between;">
          <h4 class="card-title">Manage Banner</h4>
          <a href="{% url 'adminshome:add_banner' %}"><button type="button" class="btn btn-danger btn-icon-text">
              <i class="mdi mdi-plus btn-icon-prepend"></i> Add </button></a>
        </div>
        <div class="table-responsive">
          {% if banners %}
          <table class="table table-bordered" style="background-color: #f2f2f2;">
              <thead>
                  <tr>
                      <th> Name </th>
                      <th> Image </th>
                      <th> Action </th>
                  </tr>
              </thead>
              <tbody>
                  {% for banner in banners %}
                  <tr>
                      <td> {{ banner.name }} </td>
                      <td> <img src="{{ banner.image.url }}" alt="" style="width: 150px; height: auto;"> </td>
                      <td>
                          <a href="{% url 'adminshome:edit_banner' pk=banner.pk %}" class="btn-link">
                              <button type="button" class="btn btn-outline-secondary btn-icon-text custom-btn" style="background-color: grey;">Edit <i class="mdi mdi-file-check btn-icon-append"></i></button>
                          </a>
                          <a href="{% url 'adminshome:delete_banner' pk=banner.pk %}">
                            <button type="submit" class="btn btn-danger btn-icon-text">Delete <i class="mdi mdi-delete btn-icon-append"></i></button>
                          </a>
                      </td>
                  </tr>
                  {% endfor %}
              </tbody>
          </table>
          {% else %}
          No Banners Found.
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  

{% endblock %}